### ISSUE TITLE
Version 0.0.2 and 0.0.3 Not Working

### ISSUE THREAD

**Issue by 6StringSam** [michaellw/Obsidian-Canvas-Style-Menu#1]
Great plugin!

I got version 0.0.1 to work in my sandbox vault.  Versions 0.0.2 and 0.0.3 don't work.  (When changing versions, I'm deleting them from Obsidian and BRAT then closing Obsidian and making sure the plugin folder is removed.) 

I can see that the Canvas file is being updated with the class information.  Something is off in the presentation.

{
"nodes":[
	{"id":"cbad49ac8eb10882","type":"group","x":-145,"y":-50,"width":285,"height":290,"label":"Group 1"},
	{"id":"9cd7ca5fa09fda34","type":"text","text":"Default","border":"cs-border-default","x":-125,"y":-30,"width":250,"height":60},
	{"id":"362f4720e127cb48","type":"text","text":"No Boarder","border":"cs-border-none","x":-125,"y":40,"width":250,"height":60},
	{"id":"bddd465918f2bf36","type":"text","text":"Dashed","border":"cs-border-dashed","bg":"cs-bg-transparent","x":-125,"y":120,"width":250,"height":60,"color":"3"}
	],
	"edges":[]
}

Any ideas what could be going on?

Obsidian Version: 1.5.1
Theme: Default

Plugins Installed:
- BRAT
- Canvas Style Menu

CSS Snippets:
- 1 Called Canvas-Menu-Style

.canvas-node.cs-border-none .canvas-node-container {
  border: none!important;
  box-shadow: none;
}

.canvas-node.cs-border-dashed .canvas-node-container {
  border: 2px dashed rgba(var(--canvas-color), 0.5);
  box-shadow: none;
}

.canvas-node.cs-bg-transparent .canvas-node-container {
  background-color: transparent;

}

**Comment by michaellw** [comment]
My Obsidian version is 1.4.16 and it works well, could you please check the console (Ctrl + Shift + I) output of obsidian for these two messages?
![image](https://github.com/michaellw/Obsidian-Canvas-Style-Menu/assets/276357/f60cdd5b-76bb-445a-bd63-6be3db8459ad)

**Comment by michaellw** [comment]
Please check if there are no connecting lines in your canvas. This might cause issues with plugin loading. I have already made the necessary fixes. Please confirm whether this resolves the issue you were experiencing, thank you.

**Comment by 6StringSam** [comment]
**With version 0.0.3:**
Only one message in the console.  "Canvas-Style-Menu: canvas history patched".

**Now with version 0.0.4:**
Now both messages are in the console "Canvas-Style-Menu: canvas history patched" and "Canvas-Style-Menu: canvas node patched".  And it works!

Thank you!

**Comment by michaellw** [comment]
There was a bug in the plugin loading process, including the first time opening a blank canvas after each startup. It has now been fixed, and you can test it out. Thank you!
