### ISSUE TITLE
Titles of images on Canvas don`t show up

### ISSUE THREAD

**Issue by wednes78** [michaellw/Obsidian-Canvas-Style-Menu#5]
I`ve noticed if i enable this plugin, titles of images on canvas don`t show up anymore.

https://github.com/michaellw/Obsidian-Canvas-Style-Menu/assets/103387173/fd8cd100-0d47-41f0-ac90-0fef1f935b85

**Comment by michaellw** [comment]
Yes, it's hidden by default, because there are still some problems with handling the rotation. If you need to show it just add this to your css file, or find the styles.css file in the plugins folder and delete lines 77~79. Will fix this in next release.
```
.canvas-node .canvas-node-label {
  display: block;
}
```

**Comment by wednes78** [comment]
Thank you!
I tried and made sure that worked.
