### ISSUE TITLE
Remove styling

### ISSUE THREAD

**Issue by Eusorph** [michaellw/Obsidian-Canvas-Style-Menu#8]
When I apply one of the styling, if I want to undo it, I can only do it with the undo button right after the moment  I applied it. If I wan to remove it afterward or bring the note back styling to normal, I can't. All the styling buttons aren't ON/OFF but only ON.
Is there a way to remove all the styling applied on a note or arrow?

**Comment by michaellw** [comment]
Right-clicking on the button allows you to remove the style.
